<a href="https://colab.research.google.com/github/luadeprataart/Reconhecimento-de-Padroes/blob/main/2__Introducao_Scikit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula 02 - Introdução ao Scikit-Learn
#### Material baseado no livro "Practical Machine Learning with Python" Sarkar, D. (et al.) (2018)

---

# Numpy
## Arrays

In [42]:
import numpy as np
arr = np.array([1,3,4,5,6])
arr

array([1, 3, 4, 5, 6])

In [43]:
arr.shape

(5,)

In [44]:
arr.dtype

dtype('int64')

In [45]:
arr = np.array([1,'st','er',3])
arr.dtype

dtype('<U21')

In [46]:
#np.sum(arr)

### Creating arrays

In [47]:
arr = np.array([[1,2,3],[2,4,6],[8,8,8]])
arr.shape

(3, 3)

In [48]:
arr

array([[1, 2, 3],
       [2, 4, 6],
       [8, 8, 8]])

In [49]:
arr = np.zeros((2,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
arr = np.ones((2,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [51]:
arr = np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
arr = np.random.randn(3,4)
arr

array([[ 1.02864493, -0.45084489, -0.44426072,  0.66879911],
       [-0.23117473, -0.10305244,  0.46600317, -1.78344958],
       [-1.19157268, -0.20079947,  0.77738335,  0.66541441]])

### Accessing array elements
#### Simple indexing

In [53]:
arr[1]

array([-0.23117473, -0.10305244,  0.46600317, -1.78344958])

In [54]:
arr = np.arange(12).reshape(2,2,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [55]:
arr[0]

array([[0, 1, 2],
       [3, 4, 5]])

In [56]:
arr = np.arange(10)
arr[5:]


array([5, 6, 7, 8, 9])

In [57]:
arr[5:8]

array([5, 6, 7])

In [58]:
arr[:-5]

array([0, 1, 2, 3, 4])

In [59]:
arr = np.arange(12).reshape(2,2,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [60]:
arr[1:2]

array([[[ 6,  7,  8],
        [ 9, 10, 11]]])

In [61]:
arr = np.arange(27).reshape(3,3,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [62]:
arr[:,:,2]

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [63]:
arr[...,2]

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

#### Advanced Indexing

In [64]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [65]:
arr[[0,1,2],[1,0,0]]

array([1, 3, 6])

##### Boolean Indexing

In [66]:
cities = np.array(["delhi","banglaore","mumbai","chennai","bhopal"])
city_data = np.random.randn(5,3)
city_data

array([[ 0.46654363, -0.58530431,  1.16927826],
       [-1.22814006, -0.9434083 ,  2.01406438],
       [ 0.34538538,  0.86122362, -1.68284237],
       [ 2.01735609, -0.96392359, -0.47296371],
       [-0.72783888, -0.06232878, -0.07343913]])

In [67]:
city_data[cities =="delhi"]

array([[ 0.46654363, -0.58530431,  1.16927826]])

In [68]:
city_data[city_data >0]

array([0.46654363, 1.16927826, 2.01406438, 0.34538538, 0.86122362,
       2.01735609])

In [69]:
city_data[city_data >0] = 0
city_data


array([[ 0.        , -0.58530431,  0.        ],
       [-1.22814006, -0.9434083 ,  0.        ],
       [ 0.        ,  0.        , -1.68284237],
       [ 0.        , -0.96392359, -0.47296371],
       [-0.72783888, -0.06232878, -0.07343913]])

#### Operations on arrays

In [70]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [71]:
arr + 5

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [72]:
arr * 2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [73]:
arr1 = np.arange(15).reshape(5,3)
arr2 = np.arange(5).reshape(5,1)
arr2 + arr1


array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18]])

In [74]:
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [75]:
arr2

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [76]:
arr1 = np.random.randn(5,3)
arr1

array([[-0.57015306,  1.43314468, -0.48422481],
       [-0.91645696, -0.64395991,  0.54674408],
       [-0.08217547, -3.15937934,  0.59272717],
       [-0.61506551,  1.16971558,  1.50153663],
       [ 0.16473679,  0.66205297, -0.02484883]])

In [77]:
np.modf(arr1)

(array([[-0.57015306,  0.43314468, -0.48422481],
        [-0.91645696, -0.64395991,  0.54674408],
        [-0.08217547, -0.15937934,  0.59272717],
        [-0.61506551,  0.16971558,  0.50153663],
        [ 0.16473679,  0.66205297, -0.02484883]]),
 array([[-0.,  1., -0.],
        [-0., -0.,  0.],
        [-0., -3.,  0.],
        [-0.,  1.,  1.],
        [ 0.,  0., -0.]]))

#### Linear algebra using numpy

In [78]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[1,2,3]])
A.dot(B)

array([[ 24,  24,  24],
       [ 72,  69,  66],
       [120, 114, 108]])

In [79]:
A = np.arange(15).reshape(3,5)
A.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

# Pandas
## Data frames

In [80]:
import pandas as pd
d =  [{'city':'Delhi',"data":1000},
      {'city':'Banglaore',"data":2000},
      {'city':'Mumbai',"data":1000}]
pd.DataFrame(d)

city  data
0      Delhi  1000
1  Banglaore  2000
2     Mumbai  1000

In [81]:
df = pd.DataFrame(d)

### Reading in data

In [82]:
city_data = pd.read_csv(filepath_or_buffer='simplemaps-worldcities-basic.csv')

In [83]:
city_data.head(n=10)

city      city_ascii        lat        lng       pop  \
0   Qal eh-ye Now       Qal eh-ye  34.983000  63.133300    2997.0   
1     Chaghcharan     Chaghcharan  34.516701  65.250001   15000.0   
2     Lashkar Gah     Lashkar Gah  31.582998  64.360000  201546.0   
3          Zaranj          Zaranj  31.112001  61.886998   49851.0   
4      Tarin Kowt      Tarin Kowt  32.633298  65.866699   10000.0   
5    Zareh Sharan    Zareh Sharan  32.850000  68.416705   13737.0   
6        Asadabad        Asadabad  34.866000  71.150005   48400.0   
7         Taloqan         Taloqan  36.729999  69.540004   64256.0   
8  Mahmud-E Eraqi  Mahmud-E Eraqi  35.016696  69.333301    7407.0   
9      Mehtar Lam      Mehtar Lam  34.650000  70.166701   17345.0   

       country iso2 iso3 province  
0  Afghanistan   AF  AFG  Badghis  
1  Afghanistan   AF  AFG     Ghor  
2  Afghanistan   AF  AFG  Hilmand  
3  Afghanistan   AF  AFG   Nimroz  
4  Afghanistan   AF  AFG  Uruzgan  
5  Afghanistan   AF  AFG  Paktika  
6  Afghanistan   AF  AFG    Kunar  
7  Afghanistan   AF  AFG   Takhar  
8  Afghanistan   AF  AFG   Kapisa  
9  Afghanistan   AF  AFG  Laghman

In [84]:
city_data.tail()

city   city_ascii        lat        lng        pop   country  \
7317       Mutare       Mutare -18.970019  32.650038   216785.0  Zimbabwe   
7318       Kadoma       Kadoma -18.330006  29.909947    56400.0  Zimbabwe   
7319  Chitungwiza  Chitungwiza -18.000001  31.100003   331071.0  Zimbabwe   
7320       Harare       Harare -17.817790  31.044709  1557406.5  Zimbabwe   
7321     Bulawayo     Bulawayo -20.169998  28.580002   697096.0  Zimbabwe   

     iso2 iso3          province  
7317   ZW  ZWE        Manicaland  
7318   ZW  ZWE  Mashonaland West  
7319   ZW  ZWE            Harare  
7320   ZW  ZWE            Harare  
7321   ZW  ZWE          Bulawayo

In [85]:
series_es = city_data.lat

In [86]:
type(series_es)

pandas.core.series.Series

In [87]:
series_es[1:10:2]

1    34.516701
3    31.112001
5    32.850000
7    36.729999
9    34.650000
Name: lat, dtype: float64

In [88]:
series_es[:7]

0    34.983000
1    34.516701
2    31.582998
3    31.112001
4    32.633298
5    32.850000
6    34.866000
Name: lat, dtype: float64

In [89]:
series_es[:-7315]

0    34.983000
1    34.516701
2    31.582998
3    31.112001
4    32.633298
5    32.850000
6    34.866000
Name: lat, dtype: float64

In [90]:
city_data[:7]

city    city_ascii        lat        lng       pop      country  \
0  Qal eh-ye Now     Qal eh-ye  34.983000  63.133300    2997.0  Afghanistan   
1    Chaghcharan   Chaghcharan  34.516701  65.250001   15000.0  Afghanistan   
2    Lashkar Gah   Lashkar Gah  31.582998  64.360000  201546.0  Afghanistan   
3         Zaranj        Zaranj  31.112001  61.886998   49851.0  Afghanistan   
4     Tarin Kowt    Tarin Kowt  32.633298  65.866699   10000.0  Afghanistan   
5   Zareh Sharan  Zareh Sharan  32.850000  68.416705   13737.0  Afghanistan   
6       Asadabad      Asadabad  34.866000  71.150005   48400.0  Afghanistan   

  iso2 iso3 province  
0   AF  AFG  Badghis  
1   AF  AFG     Ghor  
2   AF  AFG  Hilmand  
3   AF  AFG   Nimroz  
4   AF  AFG  Uruzgan  
5   AF  AFG  Paktika  
6   AF  AFG    Kunar

In [91]:
city_data.iloc[:5,:4]

city   city_ascii        lat        lng
0  Qal eh-ye Now    Qal eh-ye  34.983000  63.133300
1    Chaghcharan  Chaghcharan  34.516701  65.250001
2    Lashkar Gah  Lashkar Gah  31.582998  64.360000
3         Zaranj       Zaranj  31.112001  61.886998
4     Tarin Kowt   Tarin Kowt  32.633298  65.866699

In [92]:
city_data[city_data['pop'] > 10000000][city_data.columns[pd.Series(city_data.columns).str.startswith('l')]]

lat         lng
360  -34.602502  -58.397531
1171 -23.558680  -46.625020
2068  31.216452  121.436505
3098  28.669993   77.230004
3110  19.016990   72.856989
3492  35.685017  139.751407
4074  19.442442  -99.130988
4513  24.869992   66.990009
5394  55.752164   37.615523
6124  41.104996   29.010002
7071  40.749979  -73.980017

In [93]:
city_greater_10mil = city_data[city_data['pop'] > 10000000]
city_greater_10mil.rename(columns={'pop':'population'}, inplace=True)
city_greater_10mil.where(city_greater_10mil.population > 15000000)

<ipython-input-93-f1a3e95243c6>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  city_greater_10mil.rename(columns={'pop':'population'}, inplace=True)


city city_ascii        lat         lng  population country iso2 iso3  \
360      NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
1171     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
2068     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
3098     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
3110  Mumbai     Mumbai  19.016990   72.856989  15834918.0   India   IN  IND   
3492   Tokyo      Tokyo  35.685017  139.751407  22006299.5   Japan   JP  JPN   
4074     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
4513     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
5394     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
6124     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
7071     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   

         province  
360           NaN  
1171          NaN  
2068          NaN  
3098          NaN  
3110  Maharashtra  
3492        Tokyo  
4074          NaN  
4513          NaN  
5394          NaN  
6124          NaN  
7071          NaN

In [94]:
df = pd.DataFrame(np.random.randn(8, 3),
columns=['A', 'B', 'C'])

### Operations on dataframes

In [95]:
nparray = df.values
type(nparray)

numpy.ndarray

In [96]:
from numpy import nan
df.iloc[4,2] = nan

In [97]:
df

A         B         C
0 -0.199339 -0.163397 -1.539927
1  0.162699  0.189635  0.409439
2  0.933543  0.870442 -0.803749
3 -0.964303  0.543201  0.645440
4 -2.131149 -0.036251       NaN
5 -1.389818 -0.901611  0.232600
6  1.615855  0.090543  1.256891
7 -0.972666 -0.932448 -0.465248

In [98]:
df.fillna(0)

A         B         C
0 -0.199339 -0.163397 -1.539927
1  0.162699  0.189635  0.409439
2  0.933543  0.870442 -0.803749
3 -0.964303  0.543201  0.645440
4 -2.131149 -0.036251  0.000000
5 -1.389818 -0.901611  0.232600
6  1.615855  0.090543  1.256891
7 -0.972666 -0.932448 -0.465248

In [99]:
columns_numeric = ['lat','lng','pop']

In [100]:
city_data[columns_numeric].mean()

lat        20.662876
lng        10.711914
pop    265463.071633
dtype: float64

In [101]:
city_data[columns_numeric].sum()

lat    1.512936e+05
lng    7.843263e+04
pop    1.943721e+09
dtype: float64

In [102]:
city_data[columns_numeric].count()

lat    7322
lng    7322
pop    7322
dtype: int64

In [103]:
city_data[columns_numeric].median()

lat       26.792730
lng       18.617509
pop    61322.750000
dtype: float64

In [104]:
city_data[columns_numeric].quantile(0.8)

lat        46.852480
lng        89.900018
pop    269210.000000
Name: 0.8, dtype: float64

In [105]:
city_data[columns_numeric].sum(axis = 1).head()

0      3095.116300
1     15099.766702
2    201641.942998
3     49943.998999
4     10098.499997
dtype: float64

In [106]:
city_data[columns_numeric].describe()

lat          lng           pop
count  7322.000000  7322.000000  7.322000e+03
mean     20.662876    10.711914  2.654631e+05
std      29.134818    79.044615  8.287622e+05
min     -89.982894  -179.589979 -9.900000e+01
25%      -0.324710   -64.788472  1.734425e+04
50%      26.792730    18.617509  6.132275e+04
75%      43.575448    73.103628  2.001726e+05
max      82.483323   179.383304  2.200630e+07

In [107]:
city_data1 = city_data.sample(3)

### Concatanating data frames

In [108]:
city_data2 = city_data.sample(3)
city_data_combine = pd.concat([city_data1,city_data2])
city_data_combine

city      city_ascii        lat         lng       pop  \
6446          Durham          Durham  35.999959  -78.920000  257114.5   
6379           Alice           Alice  27.750462  -98.070484   21122.0   
6739     Bloomington     Bloomington  39.165657  -86.526409   85781.5   
6961  San Bernardino  San Bernardino  34.120384 -117.300034  973690.5   
5082       Tashtagol       Tashtagol  52.791751   87.867701   21902.0   
915          Marilia         Marilia -22.210028  -49.950011  191083.5   

                       country iso2 iso3        province  
6446  United States of America   US  USA  North Carolina  
6379  United States of America   US  USA           Texas  
6739  United States of America   US  USA         Indiana  
6961  United States of America   US  USA      California  
5082                    Russia   RU  RUS        Kemerovo  
915                     Brazil   BR  BRA       São Paulo

In [109]:
country_data = city_data[['iso3','country']].drop_duplicates()

In [110]:
country_data.shape

(223, 2)

In [111]:
country_data.head()

iso3         country
0    AFG     Afghanistan
33   ALD           Aland
34   ALB         Albania
60   DZA         Algeria
111  ASM  American Samoa

In [112]:
del(city_data['country'])

In [113]:
city_data.merge(country_data, 'inner').head()

city   city_ascii        lat        lng       pop iso2 iso3  \
0  Qal eh-ye Now    Qal eh-ye  34.983000  63.133300    2997.0   AF  AFG   
1    Chaghcharan  Chaghcharan  34.516701  65.250001   15000.0   AF  AFG   
2    Lashkar Gah  Lashkar Gah  31.582998  64.360000  201546.0   AF  AFG   
3         Zaranj       Zaranj  31.112001  61.886998   49851.0   AF  AFG   
4     Tarin Kowt   Tarin Kowt  32.633298  65.866699   10000.0   AF  AFG   

  province      country  
0  Badghis  Afghanistan  
1     Ghor  Afghanistan  
2  Hilmand  Afghanistan  
3   Nimroz  Afghanistan  
4  Uruzgan  Afghanistan

# Scikit-learn

In [114]:
from sklearn import datasets
diabetes = datasets.load_diabetes()
X = diabetes.data[:10]
y = diabetes.target

In [115]:
X[:5]

array([[ 0.03807591,  0.05068012,  0.06169621,  0.02187239, -0.0442235 ,
        -0.03482076, -0.04340085, -0.00259226,  0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, -0.02632753, -0.00844872,
        -0.01916334,  0.07441156, -0.03949338, -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, -0.00567042, -0.04559945,
        -0.03419447, -0.03235593, -0.00259226,  0.00286131, -0.02593034],
       [-0.08906294, -0.04464164, -0.01159501, -0.03665608,  0.01219057,
         0.02499059, -0.03603757,  0.03430886,  0.02268774, -0.00936191],
       [ 0.00538306, -0.04464164, -0.03638469,  0.02187239,  0.00393485,
         0.01559614,  0.00814208, -0.00259226, -0.03198764, -0.04664087]])

In [116]:
y[:10]

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310.])

In [117]:
feature_names=['age', 'sex', 'bmi', 'bp',
               's1', 's2', 's3', 's4', 's5', 's6']

## Scikit example regression

In [118]:
from sklearn import datasets
from sklearn.linear_model import Lasso

from sklearn import linear_model, datasets
from sklearn.model_selection import GridSearchCV

diabetes = datasets.load_diabetes()
X_train = diabetes.data[:310]
y_train = diabetes.target[:310]

X_test = diabetes.data[310:]
y_test = diabetes.target[310:]

learner = Lasso(random_state=0)
alphas = np.logspace(-4, -0.5, 30)

learner.fit(X_train, y_train)

Lasso(random_state=0)

In [119]:
y_pred = learner.predict(X_test)
y_pred

array([167.65740976, 169.41733534, 129.69001805, 188.50968503,
       161.07613773, 140.22683569, 181.63125908, 147.46537223,
       156.6244556 , 162.42686029, 173.00350182, 202.95389815,
       218.21473297, 192.50670204, 175.56271442, 198.88069029,
       158.32191972, 191.0334113 , 174.08378546, 125.64157893,
       153.66199999, 128.00649334, 207.32108823, 158.86094006,
       113.02173567, 116.57138682, 208.64338664, 148.43306144,
       131.72426149, 163.30940035, 133.99719963, 163.48591879,
       150.6351001 , 137.8465945 , 149.37123585, 149.79190025,
       178.53976654, 141.80700947, 140.22683569, 109.83213345,
       196.27739144, 117.03665774, 118.86206812, 176.62489451,
       192.33941556, 136.38768825, 129.7431493 , 185.5209981 ,
        93.13905725, 158.08414225, 162.86805614, 123.87687072,
       189.1023203 , 148.98282441, 153.9221549 , 148.15695923,
       223.41792389, 222.39899953, 181.07383847, 162.62397183,
       109.83213345, 188.44708674, 139.09174823, 132.82

In [120]:
np.mean(abs(y_pred - y_test))

51.37622164032987